import { mkdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { expect, test } from '@playwright/test';
import type {} from '../../src/probe';
import { ART_REVISION } from '../../src/content/revision';

test('main 海图与本地美术修订共存 @main-integration', async ({ page, context }) => {
  test.setTimeout(900000);
  const folder = fileURLToPath(new URL('../../runs/run-20260907-review-r3/main-integration/', import.meta.url));
  mkdirSync(folder, { recursive: true });
  const errors: string[] = [];
  page.on('pageerror', e => errors.push(e.message));
  page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.goto('/');
  await expect(page.locator('[data-role="start"]')).toBeVisible();
  await page.waitForFunction(() => !!window.__nostos);
  await page.evaluate(() => window.__nostos!.gotoAct(1));
  await page.waitForFunction(() => window.__nostos!.state().phase === 'roaming');
  await page.keyboard.press('Escape');
  const panel = page.locator('.pausepanel');
  await expect(panel).toHaveCSS('opacity', '1');
  await expect(page.locator('[data-role="resume"]')).toBeFocused();
  await expect(page.locator('.review-build')).toHaveAttribute('data-revision', ART_REVISION);
  await expect(page.locator('.voyage-row')).toHaveCount(8);
  await expect(page.locator('.voyage-row[data-state="current"]')).toHaveCount(1);
  await page.waitForFunction(() => [...document.querySelectorAll<HTMLElement>('.voyage-row')].every(r => !!r.style.left));
  await page.screenshot({ path: folder + 'esc-1080p.jpg', type: 'jpeg', quality: 90 });
  console.log('Verified full entry and 1080p sea chart');
  const motion = page.locator('[data-setting="motion-pause"]');
  await expect(motion).toHaveText('ON');
  await motion.click();
  await expect(page.locator('[data-setting="motion-title"]')).toHaveText('镜头 / 流动');
  await motion.click();
  const volume = page.locator('.settings input[type="range"]').first();
  await volume.fill('0');
  await expect(volume.locator('..').locator('.value')).toHaveText('0');
  await volume.fill('1');
  await page.setViewportSize({ width: 1280, height: 720 });
  await expect(page.locator('canvas.chart')).toBeVisible();
  await expect(page.getByRole('link', { name: '打开同版资产工作台' })).toBeInViewport();
  await expect(page.locator('[data-role="resume"]')).toBeInViewport();
  await page.screenshot({ path: folder + 'esc-720p.jpg', type: 'jpeg', quality: 90 });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.locator('canvas.chart')).toBeHidden();
  await expect(page.locator('.voyage-row')).toHaveCount(8);
  await page.screenshot({ path: folder + 'esc-narrow.jpg', type: 'jpeg', quality: 90 });
  console.log('Verified settings, 720p and narrow layout');
  await page.setViewportSize({ width: 1280, height: 720 });
  const popupPromise = context.waitForEvent('page');
  await page.getByRole('link', { name: '打开同版资产工作台' }).click();
  const workbench = await popupPromise;
  workbench.on('pageerror', e => errors.push(e.message));
  await workbench.waitForLoadState('domcontentloaded');
  await expect(workbench.locator('html')).toHaveAttribute('data-revision', ART_REVISION);
  await expect(workbench.locator('#act12-hero-assets canvas')).toHaveCount(10);
  console.log('Verified same-revision workbench');
  await workbench.close();
  await page.keyboard.press('Escape');
  await expect(panel).toHaveCSS('opacity', '0');
  const before = await page.evaluate(() => window.__nostos!.state());
  expect(before.phase).toBe('roaming');
  const started = Date.now();
  for (let i = 0; i < 6; i++) await page.waitForTimeout(10000);
  const after = await page.evaluate(() => window.__nostos!.state());
  expect(after.phase).toBe('roaming');
  expect(after.frames).toBeGreaterThan(before.frames);
  expect(after.renderStats.geometries).toBe(before.renderStats.geometries);
  expect(after.renderStats.textures).toBe(before.renderStats.textures);
  await page.keyboard.press('Escape');
  await expect(panel).toHaveCSS('opacity', '1');
  await expect(page.locator('.voyage-row')).toHaveCount(8);
  writeFileSync(folder + 'report.json', JSON.stringify({ main: 'f334fe7073ae46f61b8e293f7f8ebb3f6c83b370', errors, before, after, elapsedMs: Date.now() - started, environment: 'Chromium SwiftShader; not hardware performance certification' }, null, 2));
  expect(errors).toEqual([]);
});

test('生产构建 Esc 恢复再暂停 @main-resume', async ({ page }) => {
  test.setTimeout(240000);
  const folder = fileURLToPath(new URL('../../runs/run-20260907-review-r3/main-integration/', import.meta.url));
  mkdirSync(folder, { recursive: true });
  const errors: string[] = [];
  page.on('pageerror', e => errors.push(e.message));
  page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.goto('/');
  await page.waitForFunction(() => !!window.__nostos);
  await page.evaluate(() => window.__nostos!.gotoAct(1));
  await page.waitForFunction(() => window.__nostos!.state().phase === 'roaming');
  await page.keyboard.press('Escape');
  await expect(page.locator('.pausepanel')).toHaveCSS('opacity', '1');
  await page.waitForFunction(() => [...document.querySelectorAll<HTMLElement>('.voyage-row')].every(r => !!r.style.left));
  await expect(page.locator('.voyage-row')).toHaveCount(8);
  await page.screenshot({ path: folder + 'production-esc.jpg', type: 'jpeg', quality: 90 });
  await page.keyboard.press('Escape');
  await expect(page.locator('.pausepanel')).toHaveCSS('opacity', '0');
  const before = await page.evaluate(() => window.__nostos!.state());
  expect(before.phase).toBe('roaming');
  const started = Date.now();
  for (let i = 0; i < 6; i++) await page.waitForTimeout(10000);
  const after = await page.evaluate(() => window.__nostos!.state());
  expect(after.phase).toBe('roaming');
  expect(after.frames).toBeGreaterThan(before.frames);
  expect(after.renderStats.geometries).toBe(before.renderStats.geometries);
  expect(after.renderStats.textures).toBe(before.renderStats.textures);
  await page.keyboard.press('Escape');
  await expect(page.locator('.pausepanel')).toHaveCSS('opacity', '1');
  await expect(page.locator('[data-role="resume"]')).toBeFocused();
  await expect(page.locator('.voyage-row')).toHaveCount(8);
  writeFileSync(folder + 'report.json', JSON.stringify({ main: 'f334fe7073ae46f61b8e293f7f8ebb3f6c83b370', build: 'index-1aslOchB.js', errors, before, after, elapsedMs: Date.now() - started, environment: 'isolated production preview; Chromium SwiftShader; not hardware performance certification' }, null, 2));
  expect(errors).toEqual([]);
});
